# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="edder"
DEFAULT_USER="edder"
SHOW_HOST=true

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(brew git sublime rails ruby capistrano)

source $ZSH/oh-my-zsh.sh

export BYOBU_PREFIX=$(brew --prefix)

if [ -f ~/.aliases ]; then 
	. ~/.aliases 
fi

# avoid clang errors
#export CC=/usr/bin/gc

export LC_CTYPE="en_US.UTF-8"

PATH=/usr/local/bin:$PATH:$HOME/.rvm/bin:$HOME/.bin:/usr/local/share/npm/bin # Add RVM to PATH for scripting

# notify when a command finishes, just prepend to command you wanna run with alert
alert () { "$@" && notify -message "$( echo $@ ) returned $?" -title "Command $HISTCMD Completed" >/dev/null ; }
