#!/bin/bash

sudo -v # ask for password only at the beginning


#install homebrew
ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"


#configure homebrew
brew update
brew upgrade
brew tap homebrew/versions
brew tap homebrew/dupes
brew tap josegonzalez/homebrew-php
brew tap phinze/homebrew-cask


#install cli apps
brew install coreutils git vim mackup

#install gui apps (with cask)
brew cask install adium
brew cask install disk-inventory-x
brew cask install dropbox
brew cask install firefox
brew cask install flash
brew cask install google-chrome
brew cask install hipchat
brew cask install iterm2
brew cask install node
brew cask install sequel-pro
brew cask install silverlight
brew cask install Skype
brew cask install spotify
brew cask install toggldesktop
brew cask install the-unarchiver
brew cask install vlc
brew cask install witch


#allow brew cask apps to be found via alfred
brew cask alfred link

#link sublime for global 'sublime' command
ln -s /Applications/Sublime\ Text\ 2.app/Contents/SharedSupport/bin/subl /usr/local/bin/sublime

#install capistrano
gem sources -a http://gems.github.com/