#!/bin/bash

sudo -v # ask for password only at the beginning


#install homebrew
ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"


#configure homebrew
brew update
brew upgrade
brew tap homebrew/versions
brew tap homebrew/dupes
brew tap josegonzalez/homebrew-php
brew tap phinze/homebrew-cask


#install cli apps
brew install coreutils git vim mackup

# extra libraries
brew install ack coreutils gettext jpeg macvim readline xz apple-gcc42 cowsay
brew install git libevent s-lang youtube-dl asciidoc cscope git-flow 
brew install libgpg-error mcrypt sqlite zlib autoconf ctags gnu-getopt libksba 
brew install mobile-shell tidy zsh automake curl gnu-sed libpng newt tig 
brew install autossh docbook htop-osx libtool nmap tmux bash docbook-xsl icu4c 
brew install libxml2 unixodbc brew-cask figlet iftop libxslt  
brew install pkg-config watch byobu freetype  libyaml ossp-uuid popt 
brew install wget cmake gdbm imap-uw mackup pcre protobuf xmlto 
brew install openssl imagemagick


#install gui apps (with cask)
brew cask install adium
brew cask install disk-inventory-x
brew cask install dropbox
brew cask install firefox
brew cask install flash
brew cask install bettertouchtool
brew cask install airserver
brew cask install bittorrent-sync
brew cask install google-chrome
brew cask install hipchat
brew cask install iterm2
# brew cask install node
brew cask install sequel-pro
brew cask install silverlight
brew cask install Skype
brew cask install spotify
brew cask install the-unarchiver
brew cask install vlc
brew cask install iterm2
brew cask install teleport

brew cask install smcfancontrol
brew cask install totals
brew cask install xbmc
brew cask install sshfs
brew cask install steam
brew cask install minecraft
brew cask install appcleaner 


#allow brew cask apps to be found via alfred
brew cask alfred link

#link sublime for global 'sublime' command
#ln -s /Applications/Sublime\ Text\ 2.app/Contents/SharedSupport/bin/subl /usr/local/bin/sublime

#install capistrano
gem sources -a http://gems.github.com/

#note - sticking to capistrano v2 for now...
sudo gem install capistrano
sudo gem install terminal-notifier

# install oh-my-zsh
curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

