#!/bin/bash

sudo -v # ask for password only at the beginning

brew install mariadb
brew install php55 php55-apc php55-imagick php55-intl php55-mcrypt php55-xdebug phpunit
curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin
mv /usr/local/bin/composer{.phar,}